### ISSUE TITLE
Lag between phone and app

### ISSUE THREAD

**Issue by jimmilne** [pozil/quiz-host-app#51]
I'm experiencing some severe ag between the app putting the new question on screen and the answer options appearing on the player's smart phone. In some instances the ability to answer the question finally shows on the phone when the time has elapsed to answer.

**Comment by pozil** [comment]
Hi @jimmilne, the lag you're experiencing is caused by poor network connectivity between the Heroku server and the phone.

In terms of architecture, there's only one lightweight WebSocket message that is exchanged between Heroku and the phone to triggers a game phase change like when answers appear so there's nothing I can do to in terms of code to help on this particular issue.

Note that Heroku hosts its apps in a US or EMEA datacenter. If you're far from those, that's likely to induce some latency. You decide which Heroku datacenter to use when setting up the app so make sure to pick the right one.

If switching to another Heroku datacenter does not help, you could try to host the Player app on another cloud provider that has datacenters closer to your location.
